### ISSUE TITLE
Allow to configure the rate limiter's key

### ISSUE THREAD

**Issue by dsferruzza** [AaronErhardt/actix-governor#12]
Hi!

I see that the current rate limiter's key is the peer IP address: https://github.com/AaronErhardt/actix-governor/blob/d5e7110d79bc0cb21f999a863cd6b536cb0646b2/src/lib.rs#L324 https://github.com/AaronErhardt/actix-governor/blob/d5e7110d79bc0cb21f999a863cd6b536cb0646b2/src/lib.rs#L332

I feel like this is sub-optimal for two reasons:
1. If I deploy my Actix Web app behind a reverse proxy, rate-limiting will be applied as if all incoming requests are from the same IP address (which is in fact the reverse proxy address)
2. It seems to be a good practice to set multiple rate-limiting configuration at the same time. For example, something like:
    - 1000 req/s for all requests
    - 100 req/s for requests coming from the same IP
    - 10 req/s for requests using the same API token

Concerning the first issue, Actix Web has a [method](https://docs.rs/actix-web/4.0.0-beta.14/actix_web/dev/struct.ConnectionInfo.html#method.realip_remote_addr) to extract the real user's IP if it is set by the reverse proxy in the `Forwarded` and `X-Forwarded-For` headers, but, as stated in the documentation, it is not safe to use it if we do not check if the peer address is trusted → only a trusted reverse proxy must be allowed to set these headers or else any user can fake its IP.

Because this would add quite a lot complexity to this lib, and because of my second issue, I'm thinking maybe it would be interesting to:
1. make your middleware generic over the type `T: Eq` of the rate limiter's key
2. add a `key` field in `GovernorConfig` that can take a value of type `Fn(&ServiceRequest) -> T` so that the middleware can use it to extract any key from the request

Does this make sense? What do you think?

**Comment by AaronErhardt** [comment]
I think that sounds good. Actually, the second issue shouldn't be a problem because you can already set different middlewares for different routes and therefore different rate limits, as well.
But of course the first issue is a real problem. Currently, I don't have time to write a patch for this so I'd be happy about any contribution that fixes this, especially if it doesn't add a lot of changes to the API (there should still be a good default configuration IMO).
