### ISSUE TITLE
🐙: Rate limits headers

### ISSUE THREAD

**Issue by TheAwiteb** [AaronErhardt/actix-governor#17]
There is no rate limits [headers] 😢 

[headers]: https://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers

**Comment by AaronErhardt** [comment]
Maybe I'm wrong, but it looks to me like this isn't standardized yet. Yet, if someone wants to contribute an option for enabling reasonable non-standard headers, like `x-ratelimit-limit`, I'd be happy to merge this.

**Comment by TheAwiteb** [comment]
> if someone wants to contribute an option for enabling reasonable non-standard headers, like `x-ratelimit-limit`, I'd be happy to merge this.

I'm trying to do this but I couldn't reach the max request limit and how many request are left, can you help me.

here

https://github.com/AaronErhardt/actix-governor/blob/main/src/lib.rs#L485-L488

and here

https://github.com/AaronErhardt/actix-governor/blob/main/src/lib.rs#L509-L518

**Comment by AaronErhardt** [comment]
What you need to do is to add a [StateInformationMiddleware](https://docs.rs/governor/latest/governor/middleware/struct.StateInformationMiddleware.html#) as fourth generic argument to the [RateLimiter](https://github.com/AaronErhardt/actix-governor/blob/main/src/lib.rs#L453). Ideally, the default should still be [NoOpMiddleware](https://docs.rs/governor/latest/governor/middleware/struct.NoOpMiddleware.html#) so you will likely have to add another generic type to `GovernorMiddleware`.

With the StateInformationMiddleware you should be able to get a [StateSnapshot](https://docs.rs/governor/latest/governor/middleware/struct.StateSnapshot.html#) with all the information you need. You only need to match against `Ok(state_snapshot)` here: https://github.com/AaronErhardt/actix-governor/blob/main/src/lib.rs#L485

Let me know if there are any other questions :)

**Comment by TheAwiteb** [comment]
> Let me know if there are any other questions :)

How can i fix this 🙂

![Screenshot_select-area_20220424045104](https://user-images.githubusercontent.com/59842932/164952336-6c1fc9a5-a0c8-43bd-8b78-99cfdf129187.png)

**Comment by TheAwiteb** [comment]
> How can i fix this slightly_smiling_face

yesssssss i solve it with [`with_middleware`](https://docs.rs/governor/latest/governor/state/struct.RateLimiter.html#method.with_middleware)

**Comment by TheAwiteb** [comment]
I did a PR #18 but it's incomplete, it just needs to bring the response here

https://github.com/TheAwiteb/actix-governor/blob/a910c7981f5c243d86fc7f5184b18d4bee846466/src/lib.rs#L487-L501

**Comment by TheAwiteb** [comment]
Fix in #21
