### ISSUE TITLE
The documents have not been updated

### ISSUE THREAD

**Issue by TheAwiteb** [AaronErhardt/actix-governor#28]
> https://docs.rs/actix-governor/latest/actix_governor/

The documentation is still on update 0.3.0.

and also there is no docs in  https://crates.io/

> ![image](https://user-images.githubusercontent.com/59842932/184247723-c45a8aed-d64b-4b65-b03d-83b381faaaae.png)

**Comment by AaronErhardt** [comment]
That's normal. The docs take a few minutes to build. In fact they're already updates as I'm writing this.
