### ISSUE TITLE
0.3.1 has a breaking change.

### ISSUE THREAD

**Issue by TobiasDeBruijn** [AaronErhardt/actix-governor#31]
Hi there,

One of my CI jobs failed today with the following compilation error:
```
error[E0107]: this struct takes 2 generic arguments but 1 generic argument was supplied
   --> rest/src/main.rs:116:24
    |
116 | fn ratelimit_post() -> GovernorConfig<PeerIpKeyExtractor> {
    |                        ^^^^^^^^^^^^^^ ------------------ supplied 1 generic argument
    |                        |
    |                        expected 2 generic arguments
    |
note: struct defined here, with 2 generic parameters: `K`, `M`
   --> /root/.cargo/registry/src/index.crates.io-e139d0d48fed7772/actix-governor-0.3.1/src/lib.rs:388:12
    |
388 | pub struct GovernorConfig<K: KeyExtractor, M: RateLimitingMiddleware<QuantaInstant>> {
    |            ^^^^^^^^^^^^^^ -                -
help: add missing generic argument
    |
116 | fn ratelimit_post() -> GovernorConfig<PeerIpKeyExtractor, M> {
    |                                                         +++

```
This compiled fine on `0.3.0`, but not on `0,3.1`. Code written for `0.3.0` should be compatible with `0.3.1` according to semver (I think).

IMO `0.3.1` should be yanked and republished as `0.4.0`.

Thanks!

**Comment by AaronErhardt** [comment]
Thanks for pointing this out! I totally forgot about this breaking change that is already several months old: https://github.com/AaronErhardt/actix-governor/commit/3f776ed8b1ae71dae7cc42a1ba5f82149f330a64

0.4.0-beta.1 is already out as a new version, but I tried to backport a fix to the 0.3-stable branch. I'll release 0.3.2 with a fix shortly (and yank 0.3.1), let me know if that fixes the issue for you.

**Comment by TobiasDeBruijn** [comment]
Thanks! 

This fix removes the extra generic parameter?

Thanks!

**Comment by AaronErhardt** [comment]
Can you confirm whether this fixed your CI workflow? If yes, please close this issue :)
