### ISSUE TITLE
Release 0.5.0 on crates.io?

### ISSUE THREAD

**Issue by jqnatividad** [AaronErhardt/actix-governor#46]
Hi @AaronErhardt ,

crates.io still list 0.4.1 as the latest version. Could you please publish 0.5.0?

Thanks!

**Comment by jqnatividad** [comment]
One reason to publish a new version is that 0.4.1 still uses the old governor 0.5.1 crate, which in turn, depends on the mach crate which has an unmaintained advisory -  https://rustsec.org/advisories/RUSTSEC-2020-0168

Updating governor to 0.6.0 (which you did post 0.4.1) takes care of the advisory.

**Comment by AaronErhardt** [comment]
Sorry for my inactivity over the last week, 0.5 is published now. 

In the long term, actix-governor should probably have a second maintainer because I just do FOSS stuff in my free time which can be quite limited occasionally.

**Comment by jqnatividad** [comment]
No worries @AaronErhardt ,

I'm not that deep into `actix-governor`'s inner-workings, but I'd be more than happy to help maintain it in terms of bumping dependencies in the short term and doing more as I get to learn it over time.
