### ISSUE TITLE
Getting error on new version of actix-web

### ISSUE THREAD

**Issue by Kavan72** [AaronErhardt/actix-governor#8]
I'm getting this error with new version of actix-web. i'm using `v4.0.0-beta.9`

![Screenshot from 2021-09-22 18-53-38](https://user-images.githubusercontent.com/19048640/134352049-bdf0e6a8-38e1-4f16-bb8f-adee34de45a4.png)

**Comment by AaronErhardt** [comment]
I've updated the actix web version to `v4.0.0-beta.9`. Can you check if it works now?

**Comment by Kavan72** [comment]
Nope, not working

**Comment by Kavan72** [comment]
working fine now, i was using git version of actix-web after changing to `4.0.0-beta.9` working fine
