### ISSUE TITLE
Apply the ratelimit to only certain request methods?

### ISSUE THREAD

**Issue by TobiasDeBruijn** [AaronErhardt/actix-governor#9]
Hi there,

I've run into the following scenario:
1. Ratelimit with Actix-governor
2. Browser makes too many requests
3. Eventually, an OPTIONS request will fail (and causes CORS errors),
4. Lots of errors

I think a potential solution would be to allow users to config the request method the ratelimit should apply to. E.g I might only want it on GET and POST, and maybe a different ratelimit for OPTIONS.

I could not see a way to currently do this, if there is any, please do tell!

A method to implement it could look something like this for the end user
```rs
GovernorConfigBuilder::default()
        .method(vec![Method::Get, Method::Post])
        .per_second(2)
        .burst_size(5)
        .finish()
        .unwrap(); // Save because the config is hardcoded
```
Where it by default includes all methods 

Thanks!

**Comment by AaronErhardt** [comment]
Currently this is not supported unless you only mark specific routes to use the middleware.

However, implementing this feature should be pretty simple. You can use the `ServiceRequest` here: https://github.com/AaronErhardt/actix-governor/blob/48d3552accc47cd441c3f86ffb5cb098b2b65e21/src/lib.rs#L296

You should be able to get the method using `req.head().method`
https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.ServiceRequest.html#method.head
https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.RequestHead.html#structfield.method

The rest should only require some pattern matching :)

**Comment by TobiasDeBruijn** [comment]
Yup, already on it!

**Comment by TobiasDeBruijn** [comment]
I'm also planning on backporting this for Actix ^3 support, what would you say is the best way to go about this? I was thinking forking from tag 2.2.4, then PR'ing that back

**Comment by AaronErhardt** [comment]
Yes, back porting should be pretty easy. Wait until your PR is merged and then it should be basically copy and paste. I can create an actix 3 branch for you to merge the code then.

**Comment by TobiasDeBruijn** [comment]
Sounds good!

**Comment by AaronErhardt** [comment]
I've added a new branch that should work with actix web v3: https://github.com/AaronErhardt/actix-governor/tree/actix-3

I'll then create a 0.2.5 release once the backport is merged.

**Comment by AaronErhardt** [comment]
Version 0.2.5 is out :tada:

Thanks for your contibution!

**Comment by TobiasDeBruijn** [comment]
Awesome! Time to update a whole bunch of projects! :"D
